-- AlterTable
ALTER TABLE "Humidity" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Moisture" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Temperature" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;
